config/routes.rb
Rails.application.routes.draw do

scope "(:locale)", locale: /en|de/ do
  resources :apps
end
# config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "apps#index"
end
# end translate 

  devise_for :users
  resources :categories
  resources :apps do
  resources :reviews
  end
  #root 'apps#index'

 
	resources :apps do

    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  scope "(:locale)", locale: /en|de/ do
  resources :categories
  get 'store' => 'store#index'
  get 'desc' => 'store#desc'
  get 'blind' => 'store#blind'
  get 'sight' => 'store#sight'
  get 'motorical' => 'store#motorical'
  get 'learning' => 'store#learning'
  get 'hearing' => 'store#hearing'


  match 'store/:id' => 'store#show', :as => :store_product, :via => :get

end

end

app/views/apps/_form.en.html.erb
<%= simple_form_for @app, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= f.file_field :app_img %>
	<%= f.input :name, label: "Name of the application" %>
	<%= f.input :description %>
	<%= f.input :link %>
	<%= f.input :developer %>
	<%= f.input :operation %>
	<%= f.input :price %>
	<%= f.button :submit %>

<% end %>


app/views/apps/_form.html.erb
<%= simple_form_for @app, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Wählen Sie eine Kategorie") %>
	<%= f.file_field :app_img %>
	<%= f.input :name, label: "Name der anwendung" %>
	<%= f.input :description %>
	<%= f.input :link %>
	<%= f.input :developer %>
	<%= f.input :operation %>
	<%= f.input :price %>
	<%= f.button :submit %>

<% end %>


app/views/apps/edit.en.html.erb
<h1>Edit Application</h1>

<%= simple_form_for @app, :html => { :multipart => true } do |f| %>
	<%= f.select :category_id,@categories %>
	<%= f.file_field :app_img %>
	<%= f.input :name, label: "Name of the application" %>
	<%= f.input :description %>
	<%= f.input :link %>
	<%= f.input :developer %>
	<%= f.input :operation %>
	<%= f.input :price %>
	<%= f.button :submit %>

<% end %>

app/views/apps/edit.html.erb
<h1>Anwendung Bearbeiten</h1>

<%= simple_form_for @app, :html => { :multipart => true } do |f| %>
	<%= f.select :category_id,@categories %>
	<%= f.file_field :app_img %>
	<%= f.input :name, label: "Name der anwendung" %>
	<%= f.input :description %>
	<%= f.input :link %>
	<%= f.input :developer %>
	<%= f.input :operation %>
	<%= f.input :price %>
	<%= f.button :submit %>

<% end %>

app/views/apps/index.en.html.erb
 <br></br>
 <p><a href="blind" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>

<% if params[:category].blank? && params[:search].blank? %>

	

	<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Blind %></h1></b>
	<div class="app">
		<% @apps_blind.limit(5).each do |app| %>
			<div class="col-md-2">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
		<% end %>
	</div>
	</div>

	 <br></br>

	<p><a href="sight" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
	<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Sight_Impaired %></h1></b>
	<div class="app">
		<% @apps_sight.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>
 <br></br>
<p><a href="motorical" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Motorically_Impaired %></h1></b>
	<div class="app">
		<% @apps_motorically.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>
 <br></br>
<p><a href="store#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Learning_Impaired %></h1></b>
	<div class="app">
		<% @apps_learning.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>
 <br></br>
<p><a href="store#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Hearing_Impaired %></h1></b>
	<div class="app">
		<% @apps_deaf.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>

 <br></br>
<p><a href="store#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :WheelChair %></h1></b>
	<div class="app">
		<% @apps_whealchair.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
</div>

<% elsif !params[:category].blank? && params[:search].blank? %>

<div class="row">
	<div class="app">
		<% @apps.each do |app| %>
			<div class="col-md-3">
				<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>	
		<% end %>
	</div>
	</div>

<% elsif %>
<div class="row">
	<div class="app">
		<% @apps.each do |app| %>
			<div class="col-md-3">
				<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>	
		<% end %>
	</div>
	</div>
<% end %>

  <!-- FOOTER -->
   	  <br></br>
      <br></br>
      <br></br>
      <footer align="center">
        <p class="pull-right"><a href="#"><%= image_tag("top.gif", :alt => "Back to top", :size=> "130x100" ) %></a></p>
        <p>&copy; 2016 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

<br></br>
      <br></br>
      <br></br>




<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/apps/index.html.erb

 <br></br>
 <p><a href="blind" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>

<% if params[:category].blank? && params[:search].blank? %>

	<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Blind %></h1></b>
	<div class="app">
		<% @apps_blind.limit(5).each do |app| %>
			<div class="col-md-2">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
		<% end %>
	</div>
	</div>

	 <br></br>

	<p><a href="sight" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>


	<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Sight_Impaired %></h1></b>
	<div class="app">
		<% @apps_sight.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>

 <br></br>

<p><a href="motorical" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Motorically_Impaired %></h1></b>
	<div class="app">
		<% @apps_motorically.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>
 <br></br>

<p><a href="learning" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Learning_Impaired %></h1></b>
	<div class="app">
		<% @apps_learning.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>
 <br></br>

<p><a href="store#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :Hearing_Impaired %></h1></b>
	<div class="app">
		<% @apps_deaf.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
	</div>

 <br></br>

<p><a href="store#index" target="_blank" class="btn btn-primary btn-lg" style="margin-left:900px; margin-top: 1px;">See More</a></p>
<div class="row">
	<b><h1 style="font-size:110%;"><%=t :WheelChair %></h1></b>
	<div class="app">
		<% @apps_whealchair.limit(5).each do |app| %>
			<div class="col-md-3">
			<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>
			
		<% end %>
	</div>
</div>

<% elsif !params[:category].blank? && params[:search].blank? %>

<div class="row">
	<div class="app">
		<% @apps.each do |app| %>
			<div class="col-md-3">
				<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>	
		<% end %>
	</div>
	</div>

<% elsif %>
<div class="row">
	<div class="app">
		<% @apps.each do |app| %>
			<div class="col-md-3">
				<a href="/apps/<%= app.id %>"><%= image_tag app.app_img.url(:app_index), class: "app_image" %></a>
			<p><%= link_to app.name, app_path(app) %></p>
			<p class="app-name"><%= app.price %></p>
			<div class="average-review-rating" data-score=<%= app.reviews.average(:rating) %>></div>
			</div>	
		<% end %>
	</div>
	</div>
<% end %>

  <!-- FOOTER -->
   	  <br></br>
      <br></br>
      <br></br>
      <footer align="center">
        <p class="pull-right"><a href="#"><%= image_tag("top.gif", :alt => "Back to top", :size=> "130x100" ) %></a></p>
        <p>&copy; 2016 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

<br></br>
      <br></br>
      <br></br>




<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>






app/views/apps/new.en.html.erb
<h1>New Application</h1>

<%= render 'form' %>

app/views/apps/new.html.erb
<h1>Neue Bewerbung</h1>

<%= render 'form' %>

app/views/apps/search.html.erb
<div class="row">
  <% @apps.each do |app| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag app.image.url(:medium), class: 'image'), app %>
      </div>
    </div>
  <% end %>
</div>

app/views/apps/show.en.html.erb
<div align="right">

<a href="javascript:SocialShare('https://twitter.com/share?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'https://simplesharebuttons.com/images/somacro/facebook.png', 820, 850)"> <img src="https://simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" /> </a>

<a href="javascript:SocialShare('http://www.facebook.com/sharer.php?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'https://simplesharebuttons.com/images/somacro/facebook.png', 820, 850)"><img src="https://simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" /></a>

<a href="javascript:SocialShare('http://www.linkedin.com/shareArticle?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'http://jonbennallick.co.uk/wp-content/uploads/2012/08/Facebook-logo-ICON-02.png', 820, 850)"> <img src="https://simplesharebuttons.com/images/somacro/linkedin.png" alt="LinkedIn" /></a>

<a href="javascript:SocialShare('https://plus.google.com/share?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'http://jonbennallick.co.uk/wp-content/uploads/2012/08/Facebook-logo-ICON-02.png', 820, 850)"> <img src="https://simplesharebuttons.com/images/somacro/google.png" alt="Google" /></a>

</div>

	</div>
<div class="row">
	<div class="col-md-4">
	<%= image_tag @app.app_img.url(:app_show), class: "app-show" %>
	</div>
	<div class="col-md-8">
		<div class="app-info">
		<h2 class="app-name"><%= App.human_attribute_name(:name) %>: <%= @app.name %></h2>
		<h4><%= Category.human_attribute_name(:name)%>: <%= @app.category.name %></h4>
		<h2 class="avg-rating">Average Rating</h2>
		<div class="average-review-rating" data-score=<%= @average_review %>></div>
		<span class="number-of-reviews">Based on <%= @app.reviews.count %>reviews</span>
		<p class="app-desc"><%= App.human_attribute_name(:description) %>: <%= @app.description %></p>
		<p class="app-name"><%= App.human_attribute_name(:link) %>: <a href="<%= @app.link %>"><%= @app.link %></p></a>
		<p class="app-name"><%= App.human_attribute_name(:developer)%>: <%= @app.developer %></p>
		<p class="app-name"><%= App.human_attribute_name(:operation)%>: <%= @app.operation %></p>
		<p class="app-name"><%= App.human_attribute_name(:price) %>: <%= @app.price %></p>

		<p><%= raw(youtube_embed("https://www.youtube.com/watch?v=Y7bxlR-MxxM")) %></p>

		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-4">

		<%= render @app.reviews %>
		<div>
				<%= link_to "Add Review", new_app_review_path(@app) %>
		</div>
	</div>
</div>


<%= link_to "Back", root_path %>
<% if user_signed_in? %>
	<% if @app.user_id==current_user.id %>
	<%= link_to "Edit", edit_app_path(@app) %>
	<%= link_to "Delete", app_path(@app), method: :delete, data: {confirm: "Are you sure"} %>
	<% end %>
<% end %>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>
<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>


<script>
    function SocialShare(social,url,title, descr, image, winWidth, winHeight) {
        var winTop = (screen.height / 2) - (winHeight / 2);
        var winLeft = (screen.width / 2) - (winWidth / 2);
        window.open(social+'=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url + '&p[images][0]=' + image, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight);
    }
</script>

app/views/apps/show.html.erb

<div align="right">

<a href="javascript:SocialShare('https://twitter.com/share?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'https://simplesharebuttons.com/images/somacro/facebook.png', 820, 850)"> <img src="https://simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" /> </a>

<a href="javascript:SocialShare('http://www.facebook.com/sharer.php?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'https://simplesharebuttons.com/images/somacro/facebook.png', 820, 850)"><img src="https://simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" /></a>

<a href="javascript:SocialShare('http://www.linkedin.com/shareArticle?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'http://jonbennallick.co.uk/wp-content/uploads/2012/08/Facebook-logo-ICON-02.png', 820, 850)"> <img src="https://simplesharebuttons.com/images/somacro/linkedin.png" alt="LinkedIn" /></a>

<a href="javascript:SocialShare('https://plus.google.com/share?s','https://sheltered-sierra-40726.herokuapp.com/apps/1', 'Fb Share', 'Facebook share popup', 'http://jonbennallick.co.uk/wp-content/uploads/2012/08/Facebook-logo-ICON-02.png', 820, 850)"> <img src="https://simplesharebuttons.com/images/somacro/google.png" alt="Google" /></a>

</div>


<div class="row">
	<div class="col-md-4">
	<%= image_tag @app.app_img.url(:app_show), class: "app-show" %>
	</div>
	<div class="col-md-8">
		<div class="app-info">
		<h2 class="app-name"><%= App.human_attribute_name(:name) %>: <%= @app.name %></h2>
		<h4><%= Category.human_attribute_name(:name)%>: <%= @app.category.name %></h4>
		<h2 class="avg-rating">Durchschnittliche Bewertung</h2>
		<div class="average-review-rating" data-score=<%= @average_review %>></div>
		<span class="number-of-reviews">Beyogen auf <%= @app.reviews.count %> bewertungen</span>
		<p class="app-desc"><%= App.human_attribute_name(:description) %>: <%= @app.description %></p>
		<p class="app-name"><%= App.human_attribute_name(:link) %>: <a href="<%= @app.link %>"><%= @app.link %></p></a>
		<p class="app-name"><%= App.human_attribute_name(:developer)%>: <%= @app.developer %></p>
		<p class="app-name"><%= App.human_attribute_name(:operation)%>: <%= @app.operation %></p>
		<p class="app-name"><%= App.human_attribute_name(:price) %>: <%= @app.price %></p>
		<p><%= raw(youtube_embed("https://www.youtube.com/watch?v=Y7bxlR-MxxM")) %></p>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-4">

		<%= render @app.reviews %>
		<div>
				<%= link_to "In Ansicht", new_app_review_path(@app) %>
		</div>
	</div>
</div>


<%= link_to "Zurück", root_path %>
<% if user_signed_in? %>
	<% if @app.user_id==current_user.id %>
	<%= link_to "Bearbeiten", edit_app_path(@app) %>
	<%= link_to "Löschen", app_path(@app), method: :delete, data: {confirm: "Bist du sicher?"} %>
	<% end %>
<% end %>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>
<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>


<script>
    function SocialShare(social,url,title, descr, image, winWidth, winHeight) {
        var winTop = (screen.height / 2) - (winHeight / 2);
        var winLeft = (screen.width / 2) - (winWidth / 2);
        window.open(social+'=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url + '&p[images][0]=' + image, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight);
    }
</script>