config/routes.rb
Rails.application.routes.draw do

scope "(:locale)", locale: /en|de/ do
  resources :apps
end
# config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "apps#index"
end
# end translate 

  devise_for :users
  resources :categories
  resources :apps do
  resources :reviews
  end
  #root 'apps#index'

 
	resources :apps do

    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  scope "(:locale)", locale: /en|de/ do
  resources :categories
  get 'store' => 'store#index'
  get 'desc' => 'store#desc'
  get 'blind' => 'store#blind'
  get 'sight' => 'store#sight'
  get 'motorical' => 'store#motorical'
  get 'learning' => 'store#learning'
  get 'hearing' => 'store#hearing'


  match 'store/:id' => 'store#show', :as => :store_product, :via => :get

end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :find_app
before_action :find_review, only: [:edit, :update, :destroy]
before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review=Review.new
	end

	def create
		@review=Review.new(review_params)
		@review.app_id=@app.id
		@review.user_id=current_user.id

		if @review.save
			redirect_to app_path(@app)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to app_path(@app)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to app_path(@app)
	end

	private
		def review_params
			params.require(:review).permit(:rating, :comment)
		end
		def find_app
			@app=App.find(params[:app_id])
		end
		def find_review
			@review=Review.find(params[:id])
		end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.en.html.erb
<%= simple_form_for([@app, @app.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>

<% end %>
<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>


app/views/reviews/_form.html.erb
<%= simple_form_for([@app, @app.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Wertung</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>

<% end %>
<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>


app/views/reviews/_review.en.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div
<p><%= review.comment %></p>
<p>Posted by <b><%= review.user.username %></b></p>


<% if user_signed_in? %>

	<% if review.user_id == current_user.id %>			
		<%= link_to "Edit", edit_app_review_path(review.app, review) %>
		<%= link_to "Delete", app_review_path(review.app, review), method: :delete, data: { confirm: "Are you sure?" }%>
	<% end %>	

<% end %>
		

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div
<p><%= review.comment %></p>
<p>Geschrieben von <b><%= review.user.username %></b></p>


<% if user_signed_in? %>

	<% if review.user_id == current_user.id %>			
		<%= link_to "Bearbeiten", edit_app_review_path(review.app, review) %>
		<%= link_to "Löschen", app_review_path(review.app, review), method: :delete, data: { confirm: "Bist du sicher?" }%>
	<% end %>	

<% end %>
		

app/views/reviews/edit.en.html.erb
<h1>Edit Reviews</h1>

<%= simple_form_for([@app, @review]) do |f| %>
		<div id="rating-form">
		<label>Rating</label>
		</div>
			<%= f.input :comment %>
			<%= f.button :submit %>
<% end %>	
<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/edit.html.erb
<h1>Bearbeiten Bewertung</h1>

<%= simple_form_for([@app, @review]) do |f| %>
		<div id="rating-form">
		<label>Wertung</label>
		</div>
			<%= f.input :comment %>
			<%= f.button :submit %>
<% end %>	
<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.en.html.erb
<h2>Überprüfung</h2>

<%= render 'form' %>

app/views/reviews/new.html.erb
<h2>Review</h2>

<%= render 'form' %>