config/routes.rb
Rails.application.routes.draw do

scope "(:locale)", locale: /en|de/ do
  resources :apps
end
# config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "apps#index"
end
# end translate 

  devise_for :users
  resources :categories
  resources :apps do
  resources :reviews
  end
  #root 'apps#index'

 
	resources :apps do

    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  scope "(:locale)", locale: /en|de/ do
  resources :categories
  get 'store' => 'store#index'
  get 'desc' => 'store#desc'
  get 'blind' => 'store#blind'
  get 'sight' => 'store#sight'
  get 'motorical' => 'store#motorical'
  get 'learning' => 'store#learning'
  get 'hearing' => 'store#hearing'


  match 'store/:id' => 'store#show', :as => :store_product, :via => :get

end

end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :reviews

	ransacker :average do
  		Arel.sql('average')
	end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  
  def index
	#@products = App.find(params[:id])
    if params[:category_id]
      @products = App.where(:category_id => params[:category_id])
    else
      @products = App.all
    end
    @search = App.search(params[:q])
    @products = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  	#@products = App.order(:price)  	 
  end

  def free

    @app=App.find(params[:category_id])
    @opp=App.where(price:'0') 
    @free=@app && @opp
  end

  def paid
    @app=App.find(params[:category_id])
    @pai= App.where.not(price: '0') 
    @paid=@app && @paid

  end

  def show
  	 @product = App.find(params[:id])
  end

  def blind
      @search = App.search(params[:q])
      @products = @search.result.where(:category_id => 1)     
  end

  def sight
      @search = App.search(params[:q])
      @products = @search.result.where(:category_id => 2) 
  end

  def motorical 
  	  @search = App.search(params[:q])
      @products = @search.result.where(:category_id => 3)  
  end 

  def learning
      @@search = App.search(params[:q])
      @products = @search.result.where(:category_id => 4)  
  end

  def hearing
      @search = App.search(params[:q])
      @products = @search.result.where(:category_id => 5)  
  end

   def WheelChair
      @search = App.search(params[:q])
      @products = @search.result.where(:category_id => 6)  
  end

end

app/helpers/store_helper.rb
module StoreHelper

end

app/views/store/_product.html.erb
	<section class="product">
          <h2><%= link_to product.name, store_product_path(product) %></h2>
    
          <ul><%= number_to_currency product.price %></ul>
          <td><%= image_tag product.app_img.url(:app_index) %></td>
        </dl>
        
        <td class="image-description">
          <%= image_tag product.image_url, :class => 'list-image' %>
        </td>

	</section>

app/views/store/blind.en.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

<h2> <strong> Blind english </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>
    <th><%= sort_link @search, :rating, "Review" %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>




   

app/views/store/blind.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

 <h2> <strong> Blind </strong></h2>


 <h2> <strong> Blind German </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>

    <th><%= sort_link @search, :rating, "Review",default_order: :desc %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>

app/views/store/hearing.en.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

 <h2> <strong>  Hearing Impairment </strong></h2>


 <h2> <strong> Hearing Impairment German </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>

    <th><%= sort_link @search, :rating, "Review",default_order: :desc %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>

app/views/store/hearing.html.erb
 <h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", hearing_path %></li>

<br>
<h3>Price is displayed in ascending order.</h3>


 <h2> <strong> Hearing Impairement</strong></h2>

 <div class="app">
  <% @hearing.each do |blind| %>

<div class="col-md-3">
      <a href="/apps/<%= blind.id %>"><%= image_tag blind.app_img.url(:app_index, :alt => "This is a picture"), class: "app_image"   %></a>
      <p><%= link_to blind.name, app_path(blind) %></p>
      <p class="app-name"><%= blind.price %></p>
      <div class="average-review-rating" data-score=<%= blind.reviews.average(:rating) %>></div>
      </div>
<% end %>
</div>

app/views/store/index.html.erb
<h1>Store Listing</h1>
<br>

<h1>Store Listing</h1>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>
    <th><%= sort_link @search, :rating, "Review" %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>

app/views/store/learning.en.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

 <h2> <strong> Learning </strong></h2>


 <h2> <strong> Learning Impairment German </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>

    <th><%= sort_link @search, :rating, "Review",default_order: :desc %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>

app/views/store/learning.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

 <h2> <strong> Learning </strong></h2>


 <h2> <strong> Learning Impairment German </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>

    <th><%= sort_link @search, :rating, "Review",default_order: :desc %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>

app/views/store/motorical.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

 <h2> <strong> Motorical </strong></h2>


 <h2> <strong> Motorical German </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>

    <th><%= sort_link @search, :rating, "Review",default_order: :desc %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>

app/views/store/show.html.erb
	<section class="product">
          <h2><%= link_to @product.name, store_product_path(@product) %></h2>
          
          <ul><%= number_to_currency @product.price %></ul>
        </dl>
        
        <td class="image-description">
          <td><%= image_tag @product.image.app_img.url(:app_index) %></td>
        </td>

        <% if @product.category %>
        <p>
        	<strong>Category:</strong><%= @product.category.name %>
        </p>
        <% end %>
	</section>

<p>
	<%= link_to "Home", root_path %>
</p>

app/views/store/sight.en.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

 <h2> <strong> Sight </strong></h2>


 <h2> <strong> Sight German </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>

    <th><%= sort_link @search, :rating, "Review",default_order: :desc %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>

app/views/store/sight.html.erb
<h1>Store Listing</h1>
Sort By: 
<li><%= link_to "All Products", store_path %></li>

 <h2> <strong> Sight </strong></h2>


 <h2> <strong> Sight German </strong></h2>

<table id="products">
  <tr>
    <th><%= sort_link @search, :name, "Product Name" %></th>
    <th><%= sort_link @search, :price, "Price" %></th>    
    <th><%= sort_link @search, :category_id, "Category" %></th>

    <th><%= sort_link @search, :rating, "Review",default_order: :desc %></th>
    <th><%= sort_link @search, :app_img, "Image" %></th>

  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to(product.category.name, product) %></td>
    <td><%= product.reviews.average(:rating) %></td>
    
    <td class="image-description">
        <td><%= image_tag product.app_img.url(:app_index) %></td>
    </td>
  </tr>
<% end %>
</table>